"""Generate the host skill folders from the canonical skill source, or verify they are identical (package parity).

Usage: python scripts/build_agent_adapters.py [--root DIR] [--check] [--no-codex-yaml] [--targets .claude/skills .agents/skills] [--json]

Canonical source: agent-content/skills/<name>/ (edited here only). Generated, never hand-edited:
  .claude/skills/<name>/   byte-identical copy (Claude Code discovery path)
  .agents/skills/<name>/   byte-identical copy (Codex / agent-skills discovery path)
Each generated folder also holds a marker file ``.GENERATED-DO-NOT-EDIT`` (name, source tree hash). The
.agents copy additionally gets ``agents/openai.yaml`` with implicit invocation DISABLED, unless the canonical
skill ships its own agents/openai.yaml (then that file is copied unchanged). --no-codex-yaml skips the stub.

Default mode WRITES: it creates/updates generated folders and removes stale generated folders (only folders that
carry the marker). It refuses to overwrite a folder that exists WITHOUT the marker (possible hand-made skill).
--check performs the package-parity test used by CI and writes nothing: fails when a generated folder is
missing, has extra/missing/different files (byte compare), a wrong marker, an unmarked conflicting folder, or a
stale generated folder. With no canonical skills it reports NOT_RUN. Symlinks are never used (Windows-safe copies).
Exit codes: 0 ok, 1 parity failure / conflict, 2 usage, 3 not_run with --strict.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _avc_common as C  # noqa: E402

MARKER = ".GENERATED-DO-NOT-EDIT"
DEFAULT_TARGETS = (".claude/skills", ".agents/skills")
CODEX_TARGET = ".agents/skills"
IGNORED_NAMES = {"__pycache__", ".DS_Store", "Thumbs.db", ".pytest_cache"}
IGNORED_SUFFIXES = (".pyc", ".pyo")
OPENAI_YAML = """interface:
  display_name: "{display}"
  short_description: "{short}"
policy:
  allow_implicit_invocation: false
"""


def skill_files(skill_dir: Path) -> list[str]:
    out = []
    # Sort by the POSIX relative path string: Path ordering is case-insensitive on Windows and case-sensitive elsewhere, which
    # made the tree hash (and so the marker file) differ per operating system.
    for path in sorted(skill_dir.rglob("*"), key=lambda q: q.relative_to(skill_dir).as_posix()):
        rel = path.relative_to(skill_dir)
        if any(part in IGNORED_NAMES for part in rel.parts) or path.name.endswith(IGNORED_SUFFIXES):
            continue
        if path.is_file() and not path.is_symlink():
            out.append(rel.as_posix())
    return out


_TEXT_SUFFIXES = {".md", ".py", ".json", ".jsonl", ".toml", ".yml", ".yaml", ".txt", ".html", ".css", ".js", ".csv", ".yaml"}


def _content_sha256(path: Path) -> str:
    """sha256 of the file with CRLF folded to LF for text files: a Windows checkout and a Linux checkout hash alike (git normalises to LF)."""
    data = path.read_bytes()
    if path.suffix.lower() in _TEXT_SUFFIXES:
        data = data.replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()


def tree_hash(skill_dir: Path, files: list[str]) -> str:
    digest = hashlib.sha256()
    for rel in files:
        digest.update(rel.encode("utf-8") + b"\0" + _content_sha256(skill_dir / rel).encode("ascii") + b"\n")
    return digest.hexdigest()


def marker_text(name: str, source_hash: str) -> str:
    return (
        "GENERATED by scripts/build_agent_adapters.py - DO NOT EDIT.\n"
        f"Source: agent-content/skills/{name}/\n"
        f"source_tree_sha256: {source_hash}\n"
        "Regenerate: python scripts/build_agent_adapters.py\n"
        "Verify:     python scripts/build_agent_adapters.py --check\n"
    )


def frontmatter_bits(skill_dir: Path) -> tuple[str, str]:
    name = skill_dir.name
    short = f"Skill {name}"
    try:
        fm, _, _ = C.parse_frontmatter((skill_dir / "SKILL.md").read_bytes().decode("utf-8-sig"))
        if fm and isinstance(fm.get("description"), str):
            flat = " ".join(fm["description"].split())
            short = flat.split(". ")[0][:120].replace('"', "'")
    except (C.FrontmatterError, OSError):
        pass
    return name.replace("-", " ").title(), short


def expected_extra_files(skill_dir: Path, target_rel: str, codex_yaml: bool) -> dict[str, bytes]:
    """Generated files that are not byte copies of canonical files."""
    files = skill_files(skill_dir)
    extra = {MARKER: marker_text(skill_dir.name, tree_hash(skill_dir, files)).encode("utf-8")}
    if codex_yaml and target_rel == CODEX_TARGET and "agents/openai.yaml" not in files:
        display, short = frontmatter_bits(skill_dir)
        extra["agents/openai.yaml"] = OPENAI_YAML.format(display=display, short=short).encode("utf-8")
    return extra


def canonical_skills(root: Path) -> list[Path]:
    base = root / "agent-content" / "skills"
    if not base.is_dir():
        return []
    return sorted(p for p in base.iterdir() if p.is_dir() and not p.name.startswith((".", "_")) and (p / "SKILL.md").is_file())


def safe_inside(root: Path, path: Path) -> bool:
    try:
        return path.resolve().is_relative_to(root.resolve())
    except OSError:
        return False


def compare_skill(skill_dir: Path, gen_dir: Path, extra: dict[str, bytes], target_rel: str, report: C.Report) -> None:
    label = f"{target_rel}/{skill_dir.name}"
    if not gen_dir.is_dir():
        report.fail("adapter-missing", "generated folder is missing; run build_agent_adapters.py", label)
        return
    if not (gen_dir / MARKER).is_file():
        report.fail("adapter-unmarked", f"folder exists without the {MARKER} marker (hand-made or edited?)", label)
        return
    canonical = skill_files(skill_dir)
    expected = set(canonical) | set(extra)
    actual = set(skill_files(gen_dir)) | ({MARKER} if (gen_dir / MARKER).is_file() else set())
    for rel in sorted(expected - actual):
        report.fail("adapter-file-missing", f"missing generated file '{rel}'", label)
    for rel in sorted(actual - expected):
        report.fail("adapter-file-extra", f"extra file '{rel}' (generated folders are never hand-edited)", label)
    for rel in sorted(expected & actual):
        want = extra[rel] if rel in extra else (skill_dir / rel).read_bytes()
        have = (gen_dir / rel).read_bytes()
        if want != have:
            report.fail("adapter-bytes-differ", f"'{rel}' differs from the canonical source", label)


def check(root: Path, targets: tuple[str, ...] = DEFAULT_TARGETS, codex_yaml: bool = True) -> C.Report:
    report = C.Report("build_agent_adapters")
    skills = canonical_skills(root)
    if not skills:
        report.not_run("parity", "no canonical skills found under agent-content/skills")
        return report
    names = {s.name for s in skills}
    for target_rel in targets:
        target = root / target_rel
        for skill_dir in skills:
            compare_skill(skill_dir, target / skill_dir.name, expected_extra_files(skill_dir, target_rel, codex_yaml), target_rel, report)
        if target.is_dir():
            for stale in sorted(p for p in target.iterdir() if p.is_dir() and p.name not in names and (p / MARKER).is_file()):
                report.fail("adapter-stale", "generated folder has no canonical skill any more", f"{target_rel}/{stale.name}")
    report.stats.update({"skills": len(skills), "targets": len(targets)})
    return report


def build(root: Path, targets: tuple[str, ...] = DEFAULT_TARGETS, codex_yaml: bool = True) -> C.Report:
    report = C.Report("build_agent_adapters")
    skills = canonical_skills(root)
    if not skills:
        report.not_run("build", "no canonical skills found under agent-content/skills")
        return report
    names = {s.name for s in skills}
    written = 0
    for target_rel in targets:
        target = root / target_rel
        if not safe_inside(root, target):
            report.fail("adapter-target", "target path escapes the repository root", target_rel)
            continue
        target.mkdir(parents=True, exist_ok=True)
        for stale in sorted(p for p in target.iterdir() if p.is_dir() and p.name not in names and (p / MARKER).is_file()):
            if safe_inside(root, stale):
                shutil.rmtree(stale)
                report.info("adapter-removed", "removed stale generated folder", f"{target_rel}/{stale.name}")
        for skill_dir in skills:
            gen_dir = target / skill_dir.name
            if gen_dir.exists() and not (gen_dir / MARKER).is_file():
                report.fail("adapter-unmarked", f"refusing to overwrite a folder without the {MARKER} marker", f"{target_rel}/{skill_dir.name}")
                continue
            if gen_dir.exists():
                shutil.rmtree(gen_dir)
            gen_dir.mkdir(parents=True)
            for rel in skill_files(skill_dir):
                dest = gen_dir / rel
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(skill_dir / rel, dest)
            for rel, data in expected_extra_files(skill_dir, target_rel, codex_yaml).items():
                dest = gen_dir / rel
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(data)
            written += 1
    report.stats.update({"skills": len(skills), "folders_written": written})
    verify = check(root, targets, codex_yaml)
    report.findings.extend(f for f in verify.findings if f.level == "FAIL")
    return report


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate .claude/skills and .agents/skills from agent-content/skills, or verify parity.")
    C.add_common_args(parser)
    parser.add_argument("--check", action="store_true", help="package-parity check only; write nothing")
    parser.add_argument("--no-codex-yaml", action="store_true", help="do not generate agents/openai.yaml stubs")
    parser.add_argument("--targets", nargs="+", default=list(DEFAULT_TARGETS), help="generated skill roots, relative to --root")
    return parser


def main(argv: list[str] | None = None) -> int:
    C.setup_utf8()
    args = build_parser().parse_args(argv)
    root = C.resolve_root(args.root)
    if not root.is_dir():
        print(f"error: root is not a directory: {root.name}", file=sys.stderr)
        return C.EXIT_USAGE
    targets = tuple(args.targets)
    codex_yaml = not args.no_codex_yaml
    report = check(root, targets, codex_yaml) if args.check else build(root, targets, codex_yaml)
    return C.emit(report, args.json, args.strict, args.warnings_as_errors)


if __name__ == "__main__":
    sys.exit(main())
