"""Generate SYSTEM.md (the catalogue of every skill, playbook, technique, benchmark rubric, reference and tool).

Usage: python scripts/gen_system_md.py [--root DIR] [--out SYSTEM.md] [--check] [--stdout] [--json]

Inputs (all optional; whatever is missing is listed in the output and in the report, never invented):
  agent-content/skills/*/SKILL.md  frontmatter name, description (first sentence), metadata.kind/version/status
  agent-content/playbooks/*.md     title = frontmatter title/description or the first '# ' heading
  agent-content/techniques|benchmarks|references/*.md   same title rule
  tools/*.py                       module docstring summary + ``Usage:`` line (parsed with ast, never executed)
The 'Ideal pipeline' section is the ordered list of playbooks named wf-NN-*.md.
--check regenerates in memory and fails if SYSTEM.md is missing or stale; with no inputs at all -> NOT_RUN.
Default mode writes SYSTEM.md; --stdout prints it instead (writes nothing).
Exit codes: 0 ok, 1 stale/failed, 2 usage, 3 not_run with --strict.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _avc_common as C  # noqa: E402
import gen_tools_md  # noqa: E402

HEADER = "<!-- GENERATED by scripts/gen_system_md.py from agent-content/ and tools/ - do not edit; regenerate with `python scripts/gen_system_md.py`. -->"
SECTIONS = (("playbooks", "Playbooks and workflows"), ("techniques", "Techniques"), ("benchmarks", "Benchmark rubrics"), ("references", "References (dated, volatile facts live here)"))


def first_sentence(text: str, limit: int = 220) -> str:
    flat = " ".join(text.split())
    match = re.search(r"(?<=[.!?])\s", flat)
    sentence = flat[: match.start()] if match else flat
    return (sentence[: limit - 1] + "…") if len(sentence) > limit else sentence


def md_title(path: Path) -> str:
    try:
        text = path.read_bytes().decode("utf-8-sig")
    except (OSError, UnicodeDecodeError):
        return path.stem
    try:
        fm, body, _ = C.parse_frontmatter(text)
    except C.FrontmatterError:
        fm, body = None, text
    if fm:
        for key in ("title", "description"):
            value = fm.get(key)
            if isinstance(value, str) and value.strip():
                return first_sentence(value, 140)
    for line in body.split("\n"):
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def collect_skills(root: Path, missing: list[str]) -> list[dict]:
    base = root / "agent-content" / "skills"
    if not base.is_dir():
        missing.append("agent-content/skills/ not found")
        return []
    skills = []
    for skill_dir in sorted(p for p in base.iterdir() if p.is_dir() and not p.name.startswith((".", "_"))):
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            missing.append(f"agent-content/skills/{skill_dir.name}/SKILL.md missing")
            continue
        try:
            fm, _, _ = C.parse_frontmatter(skill_md.read_bytes().decode("utf-8-sig"))
        except C.FrontmatterError as exc:
            missing.append(f"agent-content/skills/{skill_dir.name}/SKILL.md frontmatter unreadable ({exc})")
            continue
        if not fm:
            missing.append(f"agent-content/skills/{skill_dir.name}/SKILL.md has no frontmatter")
            continue
        meta = fm.get("metadata") if isinstance(fm.get("metadata"), dict) else {}
        skills.append(
            {
                "name": skill_dir.name,
                "kind": str(meta.get("kind", "")),
                "version": str(meta.get("version", "")),
                "status": str(meta.get("status", "")),
                "description": first_sentence(str(fm.get("description", ""))),
            }
        )
    return skills


def collect_docs(root: Path, folder: str, missing: list[str]) -> list[tuple[str, str]]:
    base = root / "agent-content" / folder
    if not base.is_dir():
        missing.append(f"agent-content/{folder}/ not found")
        return []
    files = sorted(p for p in base.iterdir() if p.is_file() and p.suffix.lower() == ".md" and p.name.lower() != "readme.md")
    if not files:
        missing.append(f"agent-content/{folder}/ has no .md files")
    return [(p.name, md_title(p)) for p in files]


def esc(text: str) -> str:
    return text.replace("|", "\\|")


def render(root: Path) -> tuple[str, list[str], dict]:
    missing: list[str] = []
    skills = collect_skills(root, missing)
    docs = {key: collect_docs(root, key, missing) for key, _ in SECTIONS}
    tools, reason = gen_tools_md.collect_tools(root)
    if reason:
        missing.append(reason)
    out = [HEADER, "# SYSTEM catalogue", "", "Every skill, workflow and tool in one place. Skills are specified with deterministic checks only; model evaluation has not been run (decision default Q4). Nothing here grants permission: user and project restrictions on spend, installs and publication always win.", ""]
    out += [f"## Skills ({len(skills)})", ""]
    if skills:
        out += ["| skill | kind | version | what it is for |", "|---|---|---|---|"]
        out += [f"| `{s['name']}` | {esc(s['kind'])} | {esc(s['version'])} | {esc(s['description'])} |" for s in skills]
    else:
        out.append("_No skills found._")
    for key, title in SECTIONS:
        entries = docs[key]
        out += ["", f"## {title} ({len(entries)})", ""]
        if entries:
            out += [f"- `agent-content/{key}/{name}` - {esc(t)}" for name, t in entries]
        else:
            out.append("_None found._")
    out += ["", f"## Tools ({len(tools)})", ""]
    if tools:
        out += ["| tool | purpose | usage |", "|---|---|---|"]
        for tool in tools:
            usage = " ".join(tool["usage"]) if tool["usage"] else "_missing Usage docstring_"
            out.append(f"| `tools/{tool['file']}` | {esc(tool['summary'])} | {esc(usage)} |")
    else:
        out.append("_No tools found._")
    pipeline = [(n, t) for n, t in docs["playbooks"] if re.match(r"^wf-\d\d", n)]
    out += ["", "## Ideal pipeline", ""]
    if pipeline:
        out += [f"{i}. `{n}` - {esc(t)}" for i, (n, t) in enumerate(pipeline, 1)]
    else:
        out.append("_No wf-NN playbooks found yet._")
    out += ["", "## Missing inputs when this file was generated", ""]
    out += [f"- {m} <!-- link-check-ignore -->" for m in missing] if missing else ["None."]
    counts = {"skills": len(skills), "tools": len(tools), "playbooks": len(docs["playbooks"]), "missing": len(missing)}
    return "\n".join(out) + "\n", missing, counts


def run(root: Path, out_path: Path | None = None, check: bool = False) -> tuple[C.Report, str]:
    report = C.Report("gen_system_md")
    text, missing, counts = render(root)
    nothing = counts["skills"] == 0 and counts["tools"] == 0 and counts["playbooks"] == 0
    report.stats.update(counts)
    for item in missing:
        report.warn("system-input-missing", item)
    if nothing:
        report.not_run("catalogue", "no skills, playbooks or tools found; nothing to catalogue")
        return report, ""
    target = out_path or (root / "SYSTEM.md")
    if check:
        if not target.is_file():
            report.fail("system-md-missing", "SYSTEM.md does not exist; run python scripts/gen_system_md.py")
        elif target.read_bytes().decode("utf-8") != text:
            report.fail("system-md-stale", "SYSTEM.md is stale; regenerate with python scripts/gen_system_md.py")
    return report, text


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate SYSTEM.md from agent-content/ and tools/.")
    C.add_common_args(parser)
    parser.add_argument("--out", default=None, help="output file (default <root>/SYSTEM.md)")
    parser.add_argument("--check", action="store_true", help="fail if SYSTEM.md is stale; write nothing")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing")
    return parser


def main(argv: list[str] | None = None) -> int:
    C.setup_utf8()
    args = build_parser().parse_args(argv)
    root = C.resolve_root(args.root)
    if not root.is_dir():
        print(f"error: root is not a directory: {root.name}", file=sys.stderr)
        return C.EXIT_USAGE
    out_path = Path(args.out) if args.out else None
    report, text = run(root, out_path, args.check)
    if text and args.stdout and not args.check and not args.json:
        sys.stdout.write(text)
    elif text and not args.check and not args.stdout:
        target = out_path or (root / "SYSTEM.md")
        target.write_bytes(text.encode("utf-8"))
        report.notes.append(f"wrote {target.name}")
    return C.emit(report, args.json, args.strict, args.warnings_as_errors)


if __name__ == "__main__":
    sys.exit(main())
