"""Generate docs/TOOLS.md from the ``Usage:`` docstrings of tools/*.py (the files are parsed, never executed).

Usage: python scripts/gen_tools_md.py [--root DIR] [--out docs/TOOLS.md] [--check] [--stdout] [--strict-usage] [--json]

Every tool file needs a module docstring with a ``Usage:`` line (TOOLS_SPEC.md convention 2); continuation lines
indented under it belong to the usage block. Missing inputs are reported, not hidden: a missing tools/ folder or
no tool files -> NOT_RUN; a tool without a ``Usage:`` line is listed under "Missing Usage docstring" in the output
and as a WARN (FAIL with --strict-usage).
--check regenerates in memory and fails if the output file is missing or stale (exit 1); with no inputs it is
NOT_RUN. Default mode writes the output file. --stdout prints instead of writing.
Exit codes: 0 ok, 1 stale/failed, 2 usage, 3 not_run with --strict.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _avc_common as C  # noqa: E402

HEADER = "<!-- GENERATED by scripts/gen_tools_md.py from tools/*.py docstrings - do not edit. -->"


def parse_tool(path: Path) -> dict:
    """Return {name, summary, usage: [lines], error|None} using ast only."""
    info = {"name": path.stem, "file": path.name, "summary": "", "usage": [], "error": None}
    try:
        tree = ast.parse(path.read_bytes().decode("utf-8-sig"))
    except (SyntaxError, UnicodeDecodeError, ValueError) as exc:
        info["error"] = f"cannot parse: {type(exc).__name__}"
        return info
    doc = ast.get_docstring(tree)
    if not doc:
        info["error"] = "no module docstring"
        return info
    lines = doc.split("\n")
    info["summary"] = lines[0].strip()
    for idx, line in enumerate(lines):
        stripped = line.strip()
        if stripped.lower().startswith("usage:"):
            usage = [stripped[len("usage:"):].strip()] if stripped[len("usage:"):].strip() else []
            for follow in lines[idx + 1:]:
                if not follow.strip():
                    break
                if follow.startswith((" ", "\t")):
                    usage.append(follow.strip())
                else:
                    break
            info["usage"] = usage
            break
    return info


def collect_tools(root: Path) -> tuple[list[dict], str | None]:
    tools_dir = root / "tools"
    if not tools_dir.is_dir():
        return [], "tools/ folder not found"
    files = sorted(p for p in tools_dir.glob("*.py") if p.name != "__init__.py" and not p.name.startswith("_"))
    if not files:
        return [], "tools/ has no tool files (*.py)"
    return [parse_tool(p) for p in files], None


def render(tools: list[dict]) -> str:
    out = [HEADER, "# Tools", "", f"{len(tools)} tool(s). Generated from each tool's module docstring (`Usage:` line). Run any tool with `--help`.", ""]
    out += ["| tool | purpose | usage |", "|---|---|---|"]
    for tool in tools:
        usage = "<br>".join(f"`{u}`" for u in tool["usage"]) if tool["usage"] else "_missing_"
        out.append(f"| `{tool['name']}` | {tool['summary'].replace('|', '/') or '_no summary_'} | {usage} |")
    missing = [t for t in tools if not t["usage"]]
    out += ["", "## Missing Usage docstring", ""]
    if not missing:
        out.append("None.")
    else:
        out += [f"- `{t['file']}`: {t['error'] or 'no `Usage:` line in the module docstring'}" for t in missing]
    return "\n".join(out) + "\n"


def run(root: Path, out_path: Path | None = None, check: bool = False, strict_usage: bool = False) -> tuple[C.Report, str]:
    report = C.Report("gen_tools_md")
    tools, reason = collect_tools(root)
    if reason:
        report.not_run("tools", reason)
        return report, ""
    text = render(tools)
    for tool in tools:
        if not tool["usage"]:
            (report.fail if strict_usage else report.warn)("tool-usage-missing", tool["error"] or "no `Usage:` line in the module docstring", f"tools/{tool['file']}")
    report.stats["tools"] = len(tools)
    target = out_path or (root / "docs" / "TOOLS.md")
    if check:
        if not target.is_file():
            report.fail("tools-md-missing", "docs/TOOLS.md does not exist; run python scripts/gen_tools_md.py")
        elif target.read_bytes().decode("utf-8") != text:
            report.fail("tools-md-stale", "docs/TOOLS.md is stale; regenerate with python scripts/gen_tools_md.py")
    return report, text


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate docs/TOOLS.md from tools/*.py Usage docstrings.")
    C.add_common_args(parser)
    parser.add_argument("--out", default=None, help="output file (default <root>/docs/TOOLS.md)")
    parser.add_argument("--check", action="store_true", help="fail if the output file is stale; write nothing")
    parser.add_argument("--stdout", action="store_true", help="print the generated markdown instead of writing")
    parser.add_argument("--strict-usage", action="store_true", help="a tool without a Usage line is a FAIL")
    return parser


def main(argv: list[str] | None = None) -> int:
    C.setup_utf8()
    args = build_parser().parse_args(argv)
    root = C.resolve_root(args.root)
    if not root.is_dir():
        print(f"error: root is not a directory: {root.name}", file=sys.stderr)
        return C.EXIT_USAGE
    out_path = Path(args.out) if args.out else None
    report, text = run(root, out_path, args.check, args.strict_usage)
    if text and args.stdout and not args.check and not args.json:
        sys.stdout.write(text)
    elif text and not args.check and not args.stdout:
        target = out_path or (root / "docs" / "TOOLS.md")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(text.encode("utf-8"))
        report.notes.append(f"wrote {target.name}")
    return C.emit(report, args.json, args.strict, args.warnings_as_errors)


if __name__ == "__main__":
    sys.exit(main())
