"""Positive and negative controls for scripts/gen_tools_md.py and scripts/gen_system_md.py."""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parents[2] / "scripts"
sys.path.insert(0, str(SCRIPTS))
import _avc_common as C  # noqa: E402
import _avc_fixtures as F  # noqa: E402
import gen_system_md as S  # noqa: E402
import gen_tools_md as T  # noqa: E402

TOOLS_CLI = SCRIPTS / "gen_tools_md.py"
SYSTEM_CLI = SCRIPTS / "gen_system_md.py"


@pytest.fixture()
def root(tmp_path):
    path = tmp_path / "קורס" / "repo"
    path.mkdir(parents=True)
    return path


# ------------------------------------------------------------------ gen_tools_md


def test_tools_md_lists_usage_from_docstrings(root):
    F.make_tool(root, "frame_qa", "python tools/frame_qa.py INPUT.mp4 [--json]")
    F.write(root / "tools" / "multi.py", '"""Multi-line usage tool.\n\nUsage: python tools/multi.py A\n    python tools/multi.py B --flag\n\nMore text.\n"""\n')
    report, text = T.run(root)
    assert report.status == C.PASS and report.stats["tools"] == 2
    assert "`frame_qa`" in text and "python tools/frame_qa.py INPUT.mp4 [--json]" in text
    assert "python tools/multi.py A" in text and "python tools/multi.py B --flag" in text
    assert text.startswith("<!-- GENERATED by scripts/gen_tools_md.py")
    assert "None." in text.split("## Missing Usage docstring")[1]


def test_tools_are_parsed_never_executed(root):
    marker = root / "executed.txt"
    F.write(root / "tools" / "evil.py", f'"""Evil.\n\nUsage: python tools/evil.py\n"""\nopen({str(marker)!r}, "w").write("ran")\nraise SystemExit(7)\n')
    report, text = T.run(root)
    assert not marker.exists() and "evil" in text


def test_missing_usage_is_reported_and_strict_fails(root):
    F.write(root / "tools" / "nodoc.py", "print('x')\n")
    F.write(root / "tools" / "nousage.py", '"""Does a thing."""\n')
    F.write(root / "tools" / "broken.py", "def (:\n")
    report, text = T.run(root)
    assert report.status == C.WARN and len(report.warns) == 3
    missing = text.split("## Missing Usage docstring")[1]
    assert "nodoc.py" in missing and "nousage.py" in missing and "broken.py" in missing
    strict, _ = T.run(root, strict_usage=True)
    assert strict.status == C.FAIL


def test_private_and_init_files_are_skipped(root):
    F.make_tool(root, "real")
    F.write(root / "tools" / "__init__.py", "")
    F.write(root / "tools" / "_helpers.py", '"""helper"""\n')
    report, text = T.run(root)
    assert report.stats["tools"] == 1 and "_helpers" not in text


def test_no_tools_dir_or_files_is_not_run(root):
    report, text = T.run(root)
    assert report.status == C.NOT_RUN and text == ""
    (root / "tools").mkdir()
    assert T.run(root)[0].status == C.NOT_RUN


def test_tools_check_mode(root):
    F.make_tool(root)
    assert T.run(root, check=True)[0].status == C.FAIL  # output missing
    out = F.run_cli(TOOLS_CLI, "--root", root)
    assert out.returncode == 0 and (root / "docs" / "TOOLS.md").is_file()
    assert T.run(root, check=True)[0].status == C.PASS
    F.make_tool(root, "second", "python tools/second.py")
    stale = T.run(root, check=True)[0]
    assert stale.status == C.FAIL and "tools-md-stale" in {f.code for f in stale.fails}


def test_tools_cli_stdout_and_exit_codes(root):
    F.make_tool(root)
    t = time.monotonic()
    assert F.run_cli(TOOLS_CLI, "--help").returncode == 0 and time.monotonic() - t < 3
    shown = F.run_cli(TOOLS_CLI, "--root", root, "--stdout")
    assert shown.returncode == 0 and "frame_qa" in shown.stdout and not (root / "docs").exists()
    assert F.run_cli(TOOLS_CLI, "--root", root / "empty-nope").returncode == 2
    empty = root.parent / "e"
    empty.mkdir()
    assert F.run_cli(TOOLS_CLI, "--root", empty).returncode == 0
    assert F.run_cli(TOOLS_CLI, "--root", empty, "--strict").returncode == 3
    F.write(root / "tools" / "nousage.py", '"""x"""\n')
    assert F.run_cli(TOOLS_CLI, "--root", root, "--strict-usage", "--stdout").returncode == 1


# ------------------------------------------------------------------ gen_system_md


def test_system_md_catalogue_content_and_order(root):
    F.make_repo(root)
    F.write(root / "agent-content" / "techniques" / "clean-smooth-motion.md", "---\ntitle: Clean smooth motion\n---\n# ignored heading\n")
    F.write(root / "agent-content" / "benchmarks" / "talking-head.rubric.md", "# Talking head rubric\n")
    F.write(root / "agent-content" / "references" / "platform-specs.md", "# Platform specs (dated)\n")
    report, text = S.run(root)
    assert report.fails == [] and report.stats["skills"] == 2
    assert "## Skills (2)" in text and "`demo-skill`" in text and "`second-skill`" in text
    assert "Cut and caption a talking-head clip into a vertical reel." in text
    assert "Clean smooth motion" in text and "Talking head rubric" in text and "Platform specs (dated)" in text
    assert "`tools/frame_qa.py`" in text and "python tools/frame_qa.py INPUT.mp4 [--json]" in text
    pipeline = text.split("## Ideal pipeline")[1]
    assert pipeline.index("wf-00-intake") < pipeline.index("wf-01-build")
    assert "model evaluation has not been run" in text


def test_system_md_tolerates_missing_inputs_and_lists_them(root):
    F.make_skill(root, "only-skill")
    report, text = S.run(root)
    assert report.status == C.WARN and report.stats["skills"] == 1
    missing = text.split("## Missing inputs when this file was generated")[1]
    assert "agent-content/playbooks/ not found" in missing and "tools/ folder not found" in missing
    assert "_No wf-NN playbooks found yet._" in text


def test_system_md_reports_unreadable_skill_frontmatter(root):
    F.make_skill(root, "good-skill")
    F.write(root / "agent-content/skills/bad-skill/SKILL.md", "---\nname: bad\nname: dup\n---\n")
    F.write(root / "agent-content/skills/empty-skill" / "notes.txt", "x")
    report, text = S.run(root)
    joined = " ".join(f.message for f in report.warns)
    assert "bad-skill" in joined and "empty-skill" in joined
    assert "`good-skill`" in text and "`bad-skill`" not in text


def test_system_md_with_nothing_is_not_run(root):
    report, text = S.run(root)
    assert report.status == C.NOT_RUN and text == ""


def test_system_md_check_mode_detects_stale_and_missing(root):
    F.make_repo(root)
    assert S.run(root, check=True)[0].status == C.FAIL  # not generated yet
    assert F.run_cli(SYSTEM_CLI, "--root", root).returncode == 0
    fresh = S.run(root, check=True)[0]
    assert fresh.fails == [] and fresh.status in (C.PASS, C.WARN)  # WARN: optional folders absent in the synthetic repo
    F.make_skill(root, "third-skill")
    stale = S.run(root, check=True)[0]
    assert stale.status == C.FAIL and "system-md-stale" in {f.code for f in stale.fails}


def test_system_md_is_deterministic_and_utf8(root):
    F.make_repo(root)
    F.write(root / "agent-content/playbooks/wf-02-hebrew.md", "# תהליך עריכה בעברית\n")
    first = S.render(root)[0]
    assert first == S.render(root)[0] and "תהליך עריכה בעברית" in first
    out = F.run_cli(SYSTEM_CLI, "--root", root)
    assert out.returncode == 0
    assert (root / "SYSTEM.md").read_bytes().decode("utf-8") == first
    assert not (root / "SYSTEM.md").read_bytes().startswith(b"\xef\xbb\xbf")


def test_system_cli_exit_codes_and_json(root):
    F.make_repo(root)
    t = time.monotonic()
    assert F.run_cli(SYSTEM_CLI, "--help").returncode == 0 and time.monotonic() - t < 3
    shown = F.run_cli(SYSTEM_CLI, "--root", root, "--stdout")
    assert shown.returncode == 0 and "# SYSTEM catalogue" in shown.stdout and not (root / "SYSTEM.md").exists()
    data = json.loads(F.run_cli(SYSTEM_CLI, "--root", root, "--check", "--json").stdout)
    assert data["status"] == "FAIL" and data["exit"] == 1
    empty = root.parent / "e"
    empty.mkdir()
    assert F.run_cli(SYSTEM_CLI, "--root", empty).returncode == 0
    assert F.run_cli(SYSTEM_CLI, "--root", empty, "--strict").returncode == 3
    assert F.run_cli(SYSTEM_CLI, "--root", root / "nope").returncode == 2
